baseurl: "https://www.yopa.page/"
relativeURLs: true
languageCode: en-us
title: thats.nono
theme: "hugo-tania"
paginate: 8
googleAnalytics: G-EQ4B3K8VCL
uglyurls: true

params:
  titleLogo: images/08WeMC.png
  images:
    - images/8yRnin.png
  enableFootnotes: true
  siteName: thats.nono
  siteDesc: A blog that's gonna put your software engineering skills to the test.
  author: Yoonsoo Park
  maxCategoryToShow: 10
  socialOptions:
    email: yoonsoo@duck.com
    github: https://github.com/ypark9/yopa.page
    twitter: https://twitter.com/
  UseHugoToc: true

# permalinks:
#   post: :title

menu:
  header:
    - name: About
      url: "/about.html"
    - name: Articles
      url: "/articles.html"
  footer:
    - name: About
      url: "/about.html"
    - name: Articles
      url: "/articles.html"
    - name: GitHub
      url: "https://github.com/ypark9/yopa.page"
    - name: RSS
      url: "/index.xml"

markup:
  highlight:
    noClasses: false
    lineNos: true
  goldmark:
    renderer:
      unsafe: true

sitemap:
  changefreq: daily
  filename: sitemap.xml
  priority: 0.5

outputs:
  home: ["HTML", "RSS", "JSON"]
